//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace party.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class decoration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public decoration()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public string decoreName { get; set; }
        public string image { get; set; }
        public string des { get; set; }
        public string cost { get; set; }
        public Nullable<int> CoorId { get; set; }
        public string imageTwo { get; set; }
    
        public virtual coordinator coordinator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
    }
}
