//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace party.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialRequest
    {
        public int Id { get; set; }
        public string ClientName { get; set; }
        public string ClientPhone { get; set; }
        public string ClientAdress { get; set; }
        public string monsba { get; set; }
        public string image { get; set; }
        public string des { get; set; }
        public string date { get; set; }
        public Nullable<int> CoorId { get; set; }
    
        public virtual coordinator coordinator { get; set; }
    }
}
